name: Publish package to Maven Central
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
      
      # Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      # Grant execution permission to the Gradle wrapper script
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew_linux

      # Build the project using the Gradle wrapper
      - name: Build with Gradle
        run: ./gradlew_linux build

      # Publish to Maven Central using Gradle
      - name: Publish to Maven Central
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          ./gradlew_linux publish
