name: Publish package to Maven Central
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Cache Gradle dependencies
      - name: Setup Gradle Cache
        uses: gradle/gradle-build-action@v2

      # Grant execution permission to the Gradle wrapper script
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew_linux

      # Build the project
      - name: Build with Gradle
        run: ./gradlew_linux build

      # Publish to Maven Central
      - name: Publish to Maven Central
        env:
          SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          SIGNING_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          SIGNING_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}
        run: ./gradlew_linux publish