name: Sync Repositories

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to destination repository
        env:
          SOURCE_REPO: "bax-exchange/sdk-android"
          DESTINATION_REPO: "bax-sdk/sdk-android"
        run: |
          # Configura git
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Añade el repositorio destino como remote
          git remote add destination https://${{ secrets.SYNC_TOKEN }}@github.com/${DESTINATION_REPO}.git
          
          # Empuja todos los cambios y tags al repositorio destino
          git push destination main --force
          git push destination --tags --force